#! /bin/sh

# Import colors from pywal
. "${HOME}/.cache/wal/colors.sh"

# Panel configurations
PANEL_HEIGHT=24
PANEL_WIDTH=866
PANEL_HORIZONTAL_OFFSET=250
PANEL_VERTICAL_OFFSET=8
PANEL_FONT="Terminus"
PANEL_FIFO=/tmp/panel-fifo
PANEL_WM_NAME=bspwm_panel
geometry="640x16+640+12"

killall -9 sxhkd conky lemonbar rofi

~/Scripts/lemonbar/top_bar.py | lemonbar -B "$color0" -F "$color8" -U "$color8" -g "${geometry}" -n "$PANEL_WM_NAME" -p &

#Old lemonbar command, here in case I need it:
#~/Scripts/lemonbar/top_bar.py | lemonbar -B "$color0" -F "$color8" -U "$color8" -p -u 2 -d &

#Configure colors/automatic theming:
xrdb ~/.Xresources
wal -R &
#xrdb -merge $COLOR &

#Start companion software:
rofi rofi -modi drun,run -show run &
sxhkd &
#conky -c ~/.conky.conf &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          12
bspc config top_padding 	28

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
